### ISSUE TITLE
model ouput

### ISSUE THREAD

**Issue by alirezabayatmk** [hooshvare/parsbert#10]
It seems the model on huggingface returns the permutations of some queries (mostly when the [MASK] is at the end of the sentence). for instance when the query is "I have an [MASK]" (in farsi), the model returns two sentences as below plus the candidates of the masked word (sometimes no word candidates).
- "[CLS] I have an! [SEP]"
- "[CLS] I have an. [SEP]"

 [here is another example](https://huggingface.co/HooshvareLab/bert-base-parsbert-uncased?text=%D8%A8%D9%86%DB%8C+%D8%A2%D8%AF%D9%85+%D8%A7%D8%B9%D8%B6%D8%A7%DB%8C+%5BMASK%5D)

**Comment by m3hrdadfi** [comment]
If `[MASK]` is appeared as the last token, the model tries to predict the possible tokens in this, and similar scenarios output punctuations. To get the best results, you need to add a dot or other related punctuation in your case `[MASK] .` You probably would get your desired answers!

[Your solution](https://huggingface.co/HooshvareLab/bert-base-parsbert-uncased?text=%D8%A8%D9%86%DB%8C+%D8%A2%D8%AF%D9%85+%D8%A7%D8%B9%D8%B6%D8%A7%DB%8C+%5BMASK%5D+.)
