### ISSUE TITLE
استفاده از مدل text_classificatin & sentiment& text_summarization

### ISSUE THREAD

**Issue by ZeynabKiani** [hooshvare/parsbert#12]
من میخواستم از مدل های تحلیل احساس و طبقه بندی متن و خلاصه سازی متن هوشواره استفاده کنم منتهی اسکریپت ندیم که توضیح بده روال استفاده ازشون به چه شکله یعنی بعد اینکه مدل و توکنایزر رو لود کردیم چطور متن فارسی رو باید بهش بدیم و خروجی به شکلی هست.خوشبختانه برای  شناخت موجودیت های نامدار این اسکریپت موجود هست ولی برای بقیه من ندیدم.ممنونم میشوم اگر راهنمایی کنید

**Comment by m3hrdadfi** [comment]
برای بخش دموی مدلهای آموزش داده شده میتونید از [این نوت بوک](https://github.com/huggingface/transformers/blob/master/notebooks/03-pipelines.ipynb) ایده بگیرید فقط اسم مدل رو تغییر بدید به مدل اموزش داده شده دلخواه
برای فاین-تون کردن روی دیتاست خاص برای مسائل خاص میتونید از این کد‌ها ایده بگیرید.
- [Sentiment Analysis](https://colab.research.google.com/github/hooshvare/parsbert/blob/master/notebooks/Taaghche_Sentiment_Analysis.ipynb)
- [Text Classification](https://colab.research.google.com/github/hooshvare/parsbert/blob/master/notebooks/Taaghche_Sentiment_Analysis.ipynb)
- [Token Classification](https://github.com/huggingface/transformers/tree/master/examples/token-classification)
- [Summarization](https://github.com/huggingface/transformers/tree/master/examples/seq2seq)

**Comment by ZeynabKiani** [comment]
میخواستم مدل رو روی سیستمم ذخیره کنم که هر بار محبور نباشم دانلودش کنم چون حجمش بالاس . بخاطر همین اومدم مدل روی دیسک ذخیره کردم ، بعد که میخواستم دوباره مدل رو از روی دیسک لود کنم  خروجی هشدار زیر رو داده و نتایجی که از مدل میگریم   بد میشه اصلا که انگار رندم میشه
Some weights of BertForTokenClassification were not initialized from the model checkpoint at arman_ner_model and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

اینم از روند دانلود و ذخیره و لود مجدد مدل
pt_model = AutoModel.from_pretrained('HooshvareLab/bert-base-parsbert-armanner-uncased')
pt_model.save_pretrained("arman_ner_model")
tokenizer = AutoTokenizer.from_pretrained('HooshvareLab/bert-base-parsbert-armanner-uncased')
tokenizer.save_pretrained("arman_ner_model")

ner_model=pipeline('ner', model='arman_ner_model')

**Comment by m3hrdadfi** [comment]
اول باید نوع مدل رو مشخص کنید. دوما مدل وقتی اولین بار لود میشه در کش شما ذخیره میشه که دفعه بعد نیازی به دانلود نباشه.
و سوما پیشنهاد میکنم قبل از اینکه به استفاده از مدل فکر کنید یه وقتی بزارید ای‌پی‌آی ترنسفورمرو بررسی کنید.

توی نوت بوکتون به ترتیب این خط‌ها رو اجرا کنید.

```python
!pip install -q transformers
```

```python
from __future__ import print_function
import ipywidgets as widgets
from transformers import AutoModelForSequenceClassification, AutoTokenizer, AutoConfig
from transformers import pipeline
```

```python
tokenizer = AutoTokenizer.from_pretrained("HooshvareLab/bert-fa-base-uncased-sentiment-snappfood")
config = AutoConfig.from_pretrained("HooshvareLab/bert-fa-base-uncased-sentiment-snappfood")
model = AutoModelForSequenceClassification.from_pretrained("HooshvareLab/bert-fa-base-uncased-sentiment-snappfood")
```

```python
print(config)
```

```bash
BertConfig {
  "architectures": [
    "BertForSequenceClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": "snappfood",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "HAPPY",
    "1": "SAD"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "HAPPY": 0,
    "SAD": 1
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "type_vocab_size": 2,
  "vocab_size": 100000
}
```

برای این نمونه خاص من مدل احساسات خوارک رو لود کردم. همونطور که در بخش کانفیک میبینید مدل قابلیت تشخیص احساسات دو کلاسه رو داره یا خوشحال یا ناراحت.
حالا فرض میکنم قرار سناریو ذخیره مدل رو انجام بدید که به نظرمن لازم نیست ولی خب...
من میخوام مدلمو توی دایرکتوری خاص ذخیره کنم

```python
model.save_pretrained("/content/HooshvareLab-bert-fa-base-uncased-sentiment-snappfood")
tokenizer.save_pretrained("/content/HooshvareLab-bert-fa-base-uncased-sentiment-snappfood")
```

و در پایان لود مدل و نتیجه گیری

```python
nlp_sentence_classif = pipeline('sentiment-analysis', model="/content/HooshvareLab-bert-fa-base-uncased-sentiment-snappfood/")
nlp_sentence_classif('این خوراک به شدت خوشمزه است')
```
و نتیجه خروجی

```bash
[{'label': 'HAPPY', 'score': 0.9949201941490173}]
```
