### ISSUE TITLE
How can I install parsbert

### ISSUE THREAD

**Issue by ofskymohsen** [hooshvare/parsbert#2]
How can I install Parsbert in Ubuntu 20.04? Where is it's source code?

**Comment by m3hrdadfi** [comment]
Hi,

Please follow this instruction for installing the [Transformers](https://huggingface.co/transformers/installation.html)! Whenever the transformers' package is installed, config the `HooshvareLab/bert-base-parsbert-uncased` as your model name to use ParsBERT benefits in your NLP tasks.
