### ISSUE TITLE
why ParsBert ['UNK'] into English numbers

### ISSUE THREAD

**Issue by Mary-NJ** [hooshvare/parsbert#8]
I try to run a model that uses from pre-trained Bert, I prefer to replace Pars Bert as pre-trained model, because my data is in Persian...
the model's prediction contains some ["UNK"] token's instead of numbers and it make the prediction False( since the model is using the exact match accuracy and the ["UNK"] token's make the prediction differ from the gold_true_value)
as i said here: https://stackoverflow.com/users/10623022/maryami-najafi
is there any body to help?

**Comment by MaryNJ** [comment]
update:  I try to normalizing data with HAZM , it solve the numbers UNK token but still  I have the UNK problem with also output of model  
as you see in below, the first list in dictionary is model prediction and the second list is the true value, my question is that how can I get ride of UNK's of ParsBERT output?
{"conversation581.json_-1": [["flight_search.price_range_ارزانترین [UNK] [UNK] [UNK] [UNK] [UNK] [UNK] [UNK] [UNK]", "flight_search.type_رفت و برگشت [UNK] [UNK] [UNK] [UNK] [UNK] [UNK]"], ["flight_search.price_range_ارزانترین", "flight_search.type_رفت و برگشت"]]}

**Comment by m3hrdadfi** [comment]
You can't. This is part of BERT nature! Actually, I didn't get your point! What's your input/output (what do you plan to solve)? 

Regarding your first problem, I've added some `unused` tokens for specific tasks in ParsBERT v2, and perhaps it might be a solution to such a situation.

For the next time, please be more specific!

**Comment by MaryNJ** [comment]
NO, My ParsBERT is Version 2 :)
I mean:  
for each model you have one TRUE data,( some thing like "flight_search.price_range_ارزانترین", "flight_search.type_رفت و برگشت")
and a PREDICTED data, here my data should be like TRUE one (and it IS)
it is like the TRUE + [UNK] tokens

Ofcourse I solve it, i have wrote a code when the token is convert to string and I said that:
when token == "[UNK]" ==> ignore it :)  
but I really  curious to know why the estimated output have UNK :)

**Comment by m3hrdadfi** [comment]
@MaryNJ 

You are going to pass something like this "flight_search.price_range_ارزانترین" as your input?!
And what type of issues you plan to solve (classification, regression, ...)?

For your record, ParsBERT is more a monolingual model than a multilingual one. Consider it (if you're going to deal with other languages, must use mBERT instead)?! 

To make things clear, at least for me (just in case of handling the UNK tokens), share your code (on a gist) that covers a sample of your input/output and model. I provided a template for you as bellow:

```python
# data, just a couple of samples
inputs = [
	'دیتای ورودی اول',
	'دیتای ورودی دوم',
]

# in this case a regression problem
# put yours
outputs = [
	0.5,
	1.0,
]

# your tokenizer
...


# your model 
...

# your training/evaluation
...

# your prediction
...
```
